name: pyorc

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - cartopy
  - dask
  - descartes
  - flox
  - geojson
  - geopandas
  - geos
  - jupyter
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - opencv
  - pip
  - pyproj
  - python
  - rasterio
  - requests
  - scikit-image
  - scipy
  - shapely
  - tqdm
  - typeguard
  - xarray
  - yaml
  - pip:
    - openpiv
    - git+https://github.com/localdevices/pyorc.git

